### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by liach** [tec-club/Tutorials#1]
Ryan I think you know me... Btw I am seeing who are the collaborators.

**Comment by rtolsma** [comment]
Who are you?  This is just a small repo to demo some programming concepts and language features to help teach kids at my local tec club.

**Comment by liach** [comment]
I see you from @nashafa 's following list. You know who's Daniel Leedy right? I was in his robotics last year.

**Comment by rtolsma** [comment]
Yeah I was on it last year too

**Comment by liach** [comment]
Btw what is tec club and where do you meet?

**Comment by rtolsma** [comment]
We teach coding,  it's kind of a small group but we delve into more 'programming'  than ap comp Sci does.  We meet on Fridays usually at room 233, but not this week though
